<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('ZF2 Skeleton Application')->setSeparator(' - ')->setAutoEscape(false)?>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">

        <?=$this->headLink()?>


        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>

        <!--[if lt IE 9]>
            <script type="text/javascript" src="/js/respond.min.js"></script>
            <script type="text/javascript" src="/js/html5shiv.min.js"></script>
        <![endif]-->

        <?=$this->headScript()?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home') ?>"><img src="<?=$this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;Skeleton Application</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?=$this->url('home') ?>">Home</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?=$this->content?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?=date('Y')?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div> <!-- /container -->
        <?=$this->inlineScript() ?>
    </body>
</html>
